### ISSUE TITLE
Create `/photos` page

### ISSUE THREAD

**Issue by sanman1k98** [sanman1k98/www#2]

**Comment by sanman1k98** [comment]
The kind of layout that I want is referred to as the ["Masonry" layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Masonry_layout). It's what [Unsplash](https://unsplash.com) uses.

![image](https://github.com/sanman1k98/www/assets/34922961/4bce4ab0-de7c-4da1-b996-844314f916a4)

**Comment by RajaGiddi** [comment]
Got it, lmk if I can help in anyway
